inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/features/homepage_spec.rb'
    - !ruby/regexp /old_and_unused\.rb$/
Rails:
    Enabled: true
Metrics/LineLength:
    Max: 200
Metrics/MethodLength:
    Max: 30
Metrics/ClassLength:
    Max: 200