version: '2'
services:
  db:
    image: postgres
    ports:
      - "6666:6666"
  web:
    env_file:
      - ".env.web"
    build: .
    volumes:
      - .:/lets-fish
    ports:
      - "3000:3000"
    depends_on:
      - db
