development: &default
  adapter: postgresql
  encoding: unicode
  database: lets_fish_development
  username: postgres
  pool: 5
  timeout: 5000
  host: db

test:
  <<: *default
  database: lets_fish_test