test: &test
  adapter: postgresql
  encoding: unicode
  database: lets_fish_test
  username:
  password:
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: lets_fish_development
  username:
  password:
  pool: 5
  timeout: 5000